thepath-master/thepath/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thepath.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'journeys.views.home', name='home'),
)

thepath-master/journeys/models.py
from django.db import models


class Journey(models.Model):
    """Represents a journey to learning and acheivement
    """

    name = models.CharField(max_length=50)
    description = models.TextField()

    def __unicode__(self):
        return self.name


class Trail(models.Model):
    """Represents a portion of a journey
    """

    name = models.CharField(max_length=50)
    description = models.TextField()
    url = models.URLField(null=True, blank=True)
    journey = models.ForeignKey(Journey)

    def __unicode__(self):
        return self.name

thepath-master/journeys/views.py
from django.shortcuts import render

from journeys.models import Journey


def home(request):
    journeys = Journey.objects.all()
    context = {"journeys": journeys}
    return render(request, 'journeys/home.html', context)

thepath-master/journeys/templates/journeys/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>The Path</title>
    <link rel="stylesheet" href="">
</head>
<body>
    <h1>The Path</h1>

    <table>
      <tr><th>Name</th><th>Description</th></tr>
        {% for journey in journeys %}
            <tr><td>{{journey.name}}</td><td>{{journey.description}}</td>
            {% for trail in journey.trail_set.all %}
                {% if trail.url %}
                <tr><td></td><td><a href="{{trail.url}}">{{trail.name}}</a></td></tr>
                {% else %}
                <tr><td></td><td>{{trail.name}}</td></tr>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </table>

</body>
</html>